[project]
name = "tasks-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "vegabase[async]",
  "fastapi>=0.115.8",
  "uvicorn>=0.34.0",
  "itsdangerous>=2.0.0",
  "httpx>=0.27.0",
  "aiosqlite>=0.20.0",
]
